### ISSUE TITLE
Outdated data

### ISSUE THREAD

**Issue by nikcorg** [MrLemur/parkmybike#19]
Hey,

Thanks for making this app. I absolutely love it and it's been super useful on many occasions.

However, the parking dataset is by now old and to a degree has gone stale. It is inaccurate and lacking in some places, according to my personal observations. I wonder if you might add a feature to the app to, if not add new locations, flag parking that's been removed?

I remember submitting data through a TfL portal way back when, but I don't think they're collecting it any more. I at least couldn't find the form anymore despite fervent googling and spelunking on the TfL website.

**Comment by MrLemur** [comment]
Hi @nikcorg,

I've had a look and can't see a more updated dataset, and I don't see one coming in the future with the funding problems TfL are facing.

At the moment, the app just reads from a big file of the dataset and filters it to your location, so it doesn't have the capability to add/remove information from it.

I will look into adding that feature down the line, but in the meantime you can check out [ActiveThings](https://activethings.app/bike-parking/) - they used the same dataset, but they may have more up to date information.

**Comment by nikcorg** [comment]
From what I can tell, ActiveThings have the same problem, which is logical. You're probably right in that TfL is unlikely to invest in keeping this data up to date. It's such a pity the crowdsourcing doesn't exist anymore.

Thanks for responding.
